# Configuración de red estática Ubuntu Server
# Dev: Miguel Hernandez - Hackhit
# Archivo: /etc/netplan/01-network-config.yaml
# IP Interna: 192.168.1.167
# Gateway: 192.168.1.10
# DNS: Cloudflare

network:
  version: 2
  renderer: networkd
  ethernets:
    ens18:  # Cambia por tu interfaz de red (usa: ip link show)
      addresses:
        - 192.168.1.167/24
      gateway4: 192.168.1.10
      nameservers:
        addresses:
          - 1.1.1.1                    # Cloudflare DNS IPv4 Primary
          - 1.0.0.1                    # Cloudflare DNS IPv4 Secondary
          - 2606:4700:4700::1111       # Cloudflare DNS IPv6 Primary
          - 2606:4700:4700::1001       # Cloudflare DNS IPv6 Secondary
        search: []
      dhcp4: false
      dhcp6: false
      optional: true

# Comandos para aplicar:
# sudo cp 01-network-config.yaml /etc/netplan/
# sudo netplan apply
# sudo systemctl restart systemd-networkd
